services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
      postgresql:
        condition: service_healthy
  postgresql:
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=graphqlDb
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

